language: android
cache: false
sudo: false
env:
  global:
  - ADB_INSTALL_TIMEOUT=16
android:
  components:
  - build-tools-22.0.1
  - android-21
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-21
  - sys-img-armeabi-v7a-addon-google_apis-google-21

before_install:
- chmod +x gradlew
- android list target
- echo no | android create avd --force -n test -t "Google Inc.:Google APIs:21"
  --abi google_apis/armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- chmod +x wait_for_emulator.sh
#- ./wait_for_emulator.sh
- android-wait-for-emulator
- sleep 30
- adb logcat &
- adb shell settings put secure location_providers_allowed gps,network &
- sleep 60
- adb shell input keyevent 82 &
- sleep 10
- adb shell input keyevent 22 &
- sleep 10
- adb shell input keyevent 22 &
- sleep 10
- adb shell input keyevent 23 &

script:
- "./gradlew build connectedCheck --stacktrace --continue -PdisablePreDex"


deploy:
  provider: s3
  access_key_id: "AKIAIK37DE6IWDJBWQBQ"
  secret_access_key:
    secure: "o9g7rvrHYV14Xv6gv6u6KbkKWdjRYdFOa2oNUMeKvix6U95uj3HCUDzJrTnNEs0t0+jLzLVcFaex4SvEaod2Letag3MRPuFBwrsY0ZyRNFVumqQyEzrHbYKTNhnJLi7psBrxl4SqZjjqwI3RL1jyeQsY6Onl8sHvoduaYsHu7ik="
  bucket: "geolarm"
  region: eu-central-1
  endpoint: s3-eu-central-1.amazonaws.com
  local_dir: ///home/travis/build/J-Bossi/Geolarm/app/build/outputs/
  skip_cleanup: true

