language: android
cache: false
sudo: false
env:
  global:
  - ADB_INSTALL_TIMEOUT=30
  - INSTALL_PKGS='build-tools-23.0.2,android-23'
  - UPDATE_PKGS='platform-tools,tools,extra-android-m2repository,extra-google-m2repository'
  - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"


matrix:
  include:
    - env: AVD_TARGET=android-19
    - env: AVD_TARGET=android-21
    - env: AVD_TARGET=android-23
           TARGET_PKGS=sys-img-armeabi-v7a-android-23
    - env: AVD_TARGET='Google Inc.:Google APIs:23' AVD_TAG=google_apis
           TARGET_PKGS=addon-google_apis-google-23,sys-img-armeabi-v7a-addon-google_apis-google-23
  allow_failures:
    - env: AVD_TARGET=android-23
           TARGET_PKGS=sys-img-armeabi-v7a-android-23
    - env: AVD_TARGET='Google Inc.:Google APIs:23' AVD_TAG=google_apis
           TARGET_PKGS=addon-google_apis-google-23,sys-img-armeabi-v7a-addon-google_apis-google-23
  fast_finish: true


#android:
#  components:
#  - build-tools-23.0.2
#  - android-23
#  - extra-google-google_play_services
#  - extra-google-m2repository
#  - extra-android-m2repository
#  - addon-google_apis-google-22
#  - sys-img-armeabi-v7a-addon-google_apis-google-23

before_install:
- chmod +x gradlew
- android list target
- chmod +x execute
- ./execute install-and-update-sdk
- ./execute create-and-start-device wait-for-device-online

#- echo no | android create avd --force -n test -t "Google Inc.:Google APIs:22"
#  --abi google_apis/armeabi-v7a
#- emulator -avd test -no-skin -no-audio -no-window &
#- chmod +x wait_for_emulator.sh
#- ./wait_for_emulator.sh
#- android-wait-for-emulator
#- sleep 30

before_script:
  - ./execute wait-for-device-ready
  - adb logcat &
  - adb shell settings put secure location_providers_allowed gps,network &
  - sleep 60
  - adb shell input keyevent 82 &
  - sleep 10
  - adb shell input keyevent 22 &
  - sleep 10
  - adb shell input keyevent 22 &
  - sleep 10
  - adb shell input keyevent 23 &

script:
- "./gradlew build connectedCheck --stacktrace --continue -PdisablePreDex"

after_script:

deploy:
  provider: s3
  access_key_id: "AKIAIK37DE6IWDJBWQBQ"
  secret_access_key:
    secure: "LfRO8TO0RDLWZFVOm187M8J2wrgIOf+tD6cUljgwBCVDLnTyCRNfFpq5c/14t24BX4OEudK4dFGQ0qv6by3sj0doM0fkObKMob7Cm5l8aH3va5pMANAkjESHKvtNTbGJsKTp7eg/t40i/5sFiYgH+pGWBm78ZVK+cNOWzeaYH7M="
  bucket: "geolarm"
  region: eu-central-1
  endpoint: s3-eu-central-1.amazonaws.com
  local_dir: ///home/travis/build/J-Bossi/Geolarm/app/build/outputs/
  skip_cleanup: true

