language: android
cache: false
sudo: false
env:
  global:
  - ADB_INSTALL_TIMEOUT=16
android:
  components:
  - build-tools-22.0.1
  - android-21
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-21
  - sys-img-armeabi-v7a-addon-google_apis-google-21

before_install:
- chmod +x gradlew
- android list target
- echo no | android create avd --force -n test -t "Google Inc.:Google APIs:21"
  --abi google_apis/armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &

before_script:
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:

- "./gradlew build connectedCheck --stacktrace --continue -PdisablePreDex"

after_script:
  - adb logcat &

deploy:
  provider: s3
  access_key_id: "AKIAI4YNVFFTK52NOR4A"
  secret_access_key: "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"
  bucket: "geolarm"
  region: eu-central-1
  endpoint: s3-eu-central-1.amazonaws.com
  skip_cleanup: true

